apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB4NqL0DRmKB6FWKGsB6PZ83+Lq+mnyVf53/hJer9a5HPpKZtLWFnlKK135VwSBRPqcFa+OwuR8ZMsx98yjHPxOcn4ehC6HaBL+TEhY73UpVK1rBPwR0TNlznaz+B1EPk93A0esJWFokotbjTmbYLpvCpnYSJHMemZLEvofBEnUrgoic2MRqXeWwL/v2YdyV8wLej34pQNqmOLmnjyhV6eW9FclZgkShxJaTlXDRVwp9JVvCDpVayM6mItrq2LqDuucOtWBGStq9aJw560tTOaLUZGzkNjII29ugGnq6TVQG7PK0qeyMPm5ZnYjzvFUu3XHPi4b8ur4jOX+oIyiUDP4D57D23uA8Q3CSz36UEm7iSQdQvX+QtRJ3qRGN1N6btJ+NGO/DcGafRSGeVRlAb9iYG6OySBEv3gTqrluEE78OnEFT0AC0FeMppYn+COEYQZcrUMpFfcI/w3JPN11ltx0g5G5FVmV6HxEDW1b3k+sPsUnud9Im0ONnqQO+6q/BzzDiyIRk3oIzpy7nRIMoA0ACEMln9kSlHuwag8c5k6ym8N1144YxPc+Sc/PEvvtRBoI6lhwvIoIC44ci635OwFqB3EW2BgEreszDnnEljDHZyFCvJba8+G4sYWUez/3cX7KabmK3+laaBS08w8GvYfeUFOIrJBaRZZOREN3sM3sYQI9SSlxCBUu63BgYzzQgmoQ8buI5O6c3zAtYsgqKfnwvebIOA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
