apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBa2luxc5r80PVtiOe+77+ylb8KoF28Yuxdi1FQ3jslSTV9HmY/+2RYWVgOyMnStWDO7WTFsLv16yjm2N8c50Efg29A1V+i+Zbd8kpaL40H16UWSMM2qvHRHTKNLaNcFQrwpCq2AhQBYJXLilKW5HVogHmqaKcaOpg6JT+ddzxrl8mObbDVQHileyH/hXvWY5ynMFZzUfovKfEQMbx6PrpOs4dZCwdBQz54kKaq7lb2vU8bvkUurBcadP937QX5slaAQY6KmbnQmGWLq34Fv8hyF2pWmEdZSSh1AlvnyyCULKNBsF7RSoJcyAKNKbOHes8CmAN/X3skR0eW5vMkgBMFtGraqHPFrc97IQ88kEQ58StXOcBRy+Sdyxl3mVrUF926zbrohIuC8dtszqB0Tf9EWGzymq7XnnnlYWhmOLQL+9LzNKtkhtlruBdgrkKAk/J3bwrmX0meak7rWV91KJ8wSAA5Gv6gHObhf3U9GLXCa7NfR5ICvarkM2l4WgePDTTRqRVLr1Ve3/qfBEa9+nkW6v1rRwnRqevMXKVjKlT5/rQncHHHmwQbXUCzQsGs+qMhTn4ECOHekg1oemQ2PApz3nI5rUFsAMxK21nkStl5RAbcrLEOB/nvOnsLoBIM4x76MjyorOdqA724Axr2jWESRE1OER0+PmZcbJEHN8N2y6ogBh+4BJ8U+COLxt8Cbuh/ZPXaUzt1fihdC6mBmB3VYZ5Jlg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
