apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: ishita-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: ishita
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/ishita/env/overlays
    repoURL: https://github.com/ishitasequeira/gitops13.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
