apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/ishitasequeira/gitops13.git?ref=HEAD
  creationTimestamp: null
  name: dev
spec: {}
status: {}
